mysql:
  # dsn: laravel_test:mwRMx8RKf8C53pxf@tcp(guanli.rwlb.rds.aliyuncs.com:3306)/laravel_test?charset=utf8mb4&parseTime=True&loc=Local
  dsn: root:root@tcp(127.0.0.1:3306)/user-center?charset=utf8mb4&parseTime=True&loc=Local